apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: NodePort
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
    nodePort: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-server
        imagePullPolicy: Never
        command: [ "/bin/sh", "-c" ]
        args: [ "tail -f /dev/null" ]
        env:
          - name: FTPS-USERNAME
            valueFrom:
              secretKeyRef:
                name: ftps-user
                key: username
          - name: FTPS-PASSWORD
            valueFrom:
              secretKeyRef:
                name: ftps-user
                key: password
