apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  selector:
    app: ftps
  ports:
  - name: ftp
    port: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-server
        imagePullPolicy: Never
        command: [ "/bin/sh", "-c" ]
        args: [ "tail -f /dev/null" ]
